CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "Reservations" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "TableId" integer NOT NULL,
    "StudentNumber" text NOT NULL,
    "ReservationDate" date NOT NULL,
    "StartTime" time without time zone NOT NULL,
    "EndTime" time without time zone NOT NULL,
    "IsAttended" boolean NOT NULL,
    CONSTRAINT "PK_Reservations" PRIMARY KEY ("Id")
);

CREATE TABLE "Tables" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "TableNumber" text NOT NULL,
    "FloorId" integer NOT NULL,
    CONSTRAINT "PK_Tables" PRIMARY KEY ("Id")
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251206154047_InitialCreate', '6.0.25');

COMMIT;

START TRANSACTION;

ALTER TABLE "Reservations" ADD "PenaltyProcessed" boolean NOT NULL DEFAULT FALSE;

ALTER TABLE "Reservations" ADD "StudentType" text NOT NULL DEFAULT 'Lisans';

CREATE TABLE "StudentProfiles" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "StudentNumber" text NOT NULL,
    "StudentType" text NOT NULL,
    "PenaltyPoints" integer NOT NULL,
    "BanUntil" date NULL,
    "LastNoShowProcessedAt" timestamp with time zone NULL,
    CONSTRAINT "PK_StudentProfiles" PRIMARY KEY ("Id")
);

CREATE UNIQUE INDEX "IX_StudentProfiles_StudentNumber" ON "StudentProfiles" ("StudentNumber");

UPDATE "Reservations" SET "StudentType" = 'Lisans' WHERE COALESCE(NULLIF(TRIM("StudentType"), ''), '') = '';

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251207120328_AddStudentProfileAndPenaltyFields', '6.0.25');

COMMIT;

START TRANSACTION;

ALTER TABLE "StudentProfiles" ADD "BanReason" text NULL;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251207122002_AddBanReasonToStudentProfile', '6.0.25');

COMMIT;

START TRANSACTION;

ALTER TABLE "StudentProfiles" DROP COLUMN "PenaltyPoints";

ALTER TABLE "StudentProfiles" ADD "Department" text NULL;

ALTER TABLE "StudentProfiles" ADD "ExamWeekEnd" date NULL;

ALTER TABLE "StudentProfiles" ADD "ExamWeekStart" date NULL;

ALTER TABLE "Reservations" ADD "CreatedAt" timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '-infinity';

ALTER TABLE "Reservations" ADD "Score" integer NOT NULL DEFAULT 0;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260130144219_AddScoringSystemFields', '6.0.25');

COMMIT;

START TRANSACTION;

ALTER TABLE "StudentProfiles" ADD "Faculty" text NULL;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260130160224_AddFacultyColumn', '6.0.25');

COMMIT;

START TRANSACTION;

ALTER TABLE "StudentProfiles" DROP COLUMN "ExamWeekEnd";

ALTER TABLE "StudentProfiles" DROP COLUMN "ExamWeekStart";

CREATE TABLE "ExamSchedules" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Faculty" text NOT NULL,
    "ExamWeekStart" date NOT NULL,
    "ExamWeekEnd" date NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NULL,
    CONSTRAINT "PK_ExamSchedules" PRIMARY KEY ("Id")
);

CREATE UNIQUE INDEX "IX_ExamSchedules_Faculty" ON "ExamSchedules" ("Faculty");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260130162333_AddExamScheduleTable', '6.0.25');

COMMIT;

START TRANSACTION;

DROP INDEX "IX_ExamSchedules_Faculty";

ALTER TABLE "StudentProfiles" DROP COLUMN "Faculty";

ALTER TABLE "ExamSchedules" DROP COLUMN "Faculty";

ALTER TABLE "StudentProfiles" ADD "FacultyId" integer NULL;

ALTER TABLE "ExamSchedules" ADD "FacultyId" integer NOT NULL DEFAULT 0;

CREATE TABLE "Faculties" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    CONSTRAINT "PK_Faculties" PRIMARY KEY ("Id")
);

CREATE INDEX "IX_StudentProfiles_FacultyId" ON "StudentProfiles" ("FacultyId");

CREATE UNIQUE INDEX "IX_ExamSchedules_FacultyId" ON "ExamSchedules" ("FacultyId");

CREATE UNIQUE INDEX "IX_Faculties_Name" ON "Faculties" ("Name");

ALTER TABLE "ExamSchedules" ADD CONSTRAINT "FK_ExamSchedules_Faculties_FacultyId" FOREIGN KEY ("FacultyId") REFERENCES "Faculties" ("Id") ON DELETE CASCADE;

ALTER TABLE "StudentProfiles" ADD CONSTRAINT "FK_StudentProfiles_Faculties_FacultyId" FOREIGN KEY ("FacultyId") REFERENCES "Faculties" ("Id") ON DELETE SET NULL;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260130170649_AddFacultyTable', '6.0.25');

COMMIT;

START TRANSACTION;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260131121250_AddFacultiesTableAgain', '6.0.25');

COMMIT;

